### ISSUE TITLE
Error in `par(oldpar)`: invalid value specified for graphical parameter "mai"

### ISSUE THREAD

**Issue by barracuda156** [keaven/gsDesign#90] opened 2023-06-21 07:32 UTC
```
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.8.0 (32-bit)

> library(testthat)
> library(gsDesign)
> 
> test_check("gsDesign")
Linear spending function with none = [ FAIL 2 | WARN 19 | SKIP 112 | PASS 1439 ]

══ Skipped tests ═══════════════════════════════════════════════════════════════
• On CRAN (112)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-independent-test-plot.gsDesign.R:11:3'): Test plot.gsDesign graphs are correctly rendered for plottype 1 and base R plotting package set to TRUE ──
Error in `plot.new()`: figure margins too large
Backtrace:
    ▆
 1. ├─global save_gr_plot(plot.gsDesign(x, plottype = 1, base = TRUE)) at test-independent-test-plot.gsDesign.R:11:2
 2. └─gsDesign:::plot.gsDesign(x, plottype = 1, base = TRUE)
 3.   ├─base::do.call(gsPlotName(plottype), list(x, base = base, ...))
 4.   └─gsDesign:::plotgsZ(`<gsDesign>`, base = TRUE)
 5.     └─gsDesign:::qplotit(...)
 6.       ├─base::plot(...)
 7.       └─graphics::plot.default(...)
 8.         └─graphics::plot.new()
── Error ('test-independent-test-plot.gsDesign.R:11:3'): Test plot.gsDesign graphs are correctly rendered for plottype 1 and base R plotting package set to TRUE ──
Error in `par(oldpar)`: invalid value specified for graphical parameter "mai"
Backtrace:
    ▆
 1. └─global save_gr_plot(plot.gsDesign(x, plottype = 1, base = TRUE)) at test-independent-test-plot.gsDesign.R:11:2
 2.   └─graphics::par(oldpar) at test-independent-test-plot.gsDesign.R:11:2

[ FAIL 2 | WARN 19 | SKIP 112 | PASS 1439 ]
Error: Test failures
Execution halted
```

The first too-large-margins error I have encountered before, not sure about the reason for it, but it is certainly not specific to this package.

**Comment by nanxstats** [comment] 2023-07-19 03:32
Hmm, I cannot reproduce the issue on my side.

From the appearance, these errors could occur if you are using a graphical device with a very small size, or if you have manually set an unusually large or small margin size. It's also possible that another package or code snippet modified the graphical parameters and did not restore it properly.

So, perhaps try increasing the size of the graphics device window, if you are working in a windowed environment like RStudio. Ensure the graphical parameters are using the default values before running the tests - you can check the output of `par("mai")` before running the tests.

Also, `test_check()` is normally used in `testthat.R` instead of running in console. `devtools::test()` is the usual way to run tests in console.

**Comment by nanxstats** [comment] 2023-08-07 22:02
@barracuda156 I've tried reproducing this issue multiple times but haven't been successful. Given the time and the lack of additional reports, I'm going to close this for now. Please feel free to reopen with more details if the issue persists. Thanks for your understanding.

**Closed by nanxstats** 2023-08-07 22:02 UTC

**Comment by barracuda156** [comment] 2023-08-07 22:14
@nanxstats I am sorry, turned out that even though I wanted to reply here, I did not.

Macports runs tests this way for `R` ports: https://github.com/macports/macports-ports/blob/086e28412352ebff648d9c29464f9f9418e5e5f0/_resources/port1.0/group/R-1.0.tcl#L171-L173
It works fine, and anyway would not have caused a single test to fail.

> So, perhaps try increasing the size of the graphics device window, if you are working in a windowed environment like RStudio.

I only got R GUI, but since I ran tests from the terminal, R GUI settings should likely be irrelevant.

Could you suggest how to modify the needed value manually, either from terminal or at least from R console? I could try re-running tests then.

**Comment by nanxstats** [comment] 2023-08-11 21:52
@barracuda156 Great, thanks for providing more details about the issue.

For more consistent results, I recommend aligning our setups. Using a consistent package manager and R setup simplifies debugging, especially when trying to pinpoint issues related to specific builds or configurations.

For macOS, I personally use Homebrew along with the [cask version of R](https://formulae.brew.sh/cask/r) sourced directly from the CRAN binary installer. This setup is also in line with the Mac R version used in the r-lib/actions GitHub Actions workflows.

To set this up on your machine, you can use the following commands:

```bash
brew install --cask r
```

Additionally, it might be beneficial to install XQuartz, which is mentioned in the [r-lib/actions readme](https://github.com/r-lib/actions/tree/756399d909bf9c180bbdafe8025f794f51f2da02#common-questions):

```bash
brew install --cask xquartz
```

I hope this helps. Let's see if aligning our setups addresses the issue.

**Comment by barracuda156** [comment] 2023-08-13 16:08
@nanxstats Homebrew is simply broken for older macOS (I believe, even Intel). Even if it were not, compiling everything `R` needs anew is a task for several days. Given that nothing is supported, that would require writing every port (or whatever they call their recipes for installation) from scratch and porting fixes we have in Macports. To be honest I neither have that much of time to waste nor interested to help a package manager which decided to trash its users.

**Comment by barracuda156** [comment] 2023-08-13 23:11
@nanxstats On a side note, in Macports you can install `gsDesign` as easy as `sudo port install R-gsDesign`: https://ports.macports.org/port/R-gsDesign
And this will work on every macOS from 10.5.8 up (including PowerPC systems). Homebrew? No, thanks :) 

P. S. I see `gsDesign` has been updated, I will include it in the next batch updates for R ports.
